### PR TITLE
fix(LP-200): use the real route parameter info instead of an ill-assigned constant…

### PR DESCRIPTION
**Pull request by anthonylindsay**
… for access control.

### CODE REVIEW

**Comment by Polynya** [comment]
Does this fix an issue that has been raised on the LP or LOVE boards? If not, if it's possible to test the change then can you create a ticket?

**Comment by anthonylindsay** [comment]
it's not been raised as a problem yet, but it would be once someone tried to make a new microsite. I'll make a card.

**Comment by Polynya** [comment]
I've changed the base branch to release/202408-01 so the change is tested on Preprod, when I do the next deployment.

When you have created the card please add the number to the start of the pull request title.

**Review by Polynya — APPROVED** [review]

**Comment by anthonylindsay** [comment]
@Polynya card created https://eccservicetransformation.atlassian.net/browse/LP-200

**Pull request merged**
