### PR TITLE
Allow trusted editors to use notes feature on webform submission

### PR DESCRIPTION
**Pull request by anthonylindsay**
https://eccservicetransformation.atlassian.net/browse/LOVE-358

### CODE REVIEW

**Review by Polynya — APPROVED** [review]

**Comment by Polynya** [comment]
Can you check if you've got permission to merge it @anthonylindsay ?

**Comment by anthonylindsay** [comment]
@Polynya I do! Exciting :)

**Comment by anthonylindsay** [comment]
@Polynya 
Adrian, do I need to worry about backups or anything like that or is it all idiot-proof and automatic?

**Comment by Polynya** [comment]
No backups necessary. We can always create a new branch from an earlier commit but hopefully the PRs reduce the chance of having to do that :)

**Pull request merged**
